# Generated by Django 6.0.6 on 2026-06-15 20:05

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.people.models.person_profile_photo_upload_path),
        ),
    ]
