# Generated by Django 6.0.6 on 2026-06-18 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_alter_familyinvitation_relationship_type'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('family', 'first_name', 'last_name', 'birth_date'), name='unique_person_identity'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('birth_date__isnull', True)), fields=('family', 'first_name', 'last_name'), name='unique_person_identity_no_birth_date'),
        ),
    ]
