# Generated by Django 6.0.6 on 2026-06-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_profile_photo'),
        ('people', '0002_unique_person_identity'),
    ]

    operations = [
    ]
