# Generated by GPT-5.5 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_unique_person_identity"),
        ("families", "0007_public_discovery_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("tree_members", "Tree members only"),
                    ("public_if_deceased", "Public if deceased"),
                    ("public_showcase", "Public showcase"),
                ],
                db_index=True,
                default="public_if_deceased",
                help_text="Person-level public visibility. Living people and children are still protected by public-safe serializers.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="public_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional public-safe notes for ancestor/showcase pages.",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["family", "visibility", "is_living"], name="people_pers_family__93d6aa_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["last_name", "maiden_name"], name="people_pers_last_na_6af25d_idx"),
        ),
    ]
