# Generated by Django 6.0.6 on 2026-06-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_merge_20260618_1835'),
        ('people', '0003_person_privacy_visibility'),
    ]

    operations = [
    ]
