# Generated by Django 6.0.6 on 2026-06-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_familymembership_person'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('relationship_type', models.CharField(blank=True, choices=[('parent_child', 'Parent → Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('adoptive_parent', 'Adoptive Parent'), ('guardian', 'Guardian')], default='', max_length=30)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(max_length=96, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('family', 'person'), name='unique_claimed_person_per_family'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='anchor_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_invitations_created_from', to='people.person'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='families.family'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invitee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_invitations', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['family', 'status'], name='families_fa_family__5d0556_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['invitee_email', 'status'], name='families_fa_invitee_1d6bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['token'], name='families_fa_token_7d51e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('family', 'person'), name='unique_pending_invitation_per_person'),
        ),
    ]
