# Generated by Django 6.0.6 on 2026-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_familyinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvitation',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('parent_child', 'Parent → Child'), ('spouse', 'Spouse'), ('partner', 'Partner'), ('ex_partner', 'Ex-partner'), ('sibling', 'Sibling'), ('adoptive_parent', 'Adoptive Parent'), ('step_parent', 'Step-parent'), ('guardian', 'Guardian')], default='', max_length=30),
        ),
    ]
