# Generated by GPT-5.5 Thinking on 2026-06-15

import apps.families.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0003_familyinvitation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(default=apps.families.models.make_email_verification_token, max_length=96, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=apps.families.models.default_email_verification_expiry)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="families_em_token_8b8f1a_idx"),
                    models.Index(fields=["email"], name="families_em_email_7d6f20_idx"),
                    models.Index(fields=["user", "verified_at"], name="families_em_user_02ef8b_idx"),
                ],
            },
        ),
    ]
