# Generated by GPT-5.5 Thinking on 2026-06-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0004_alter_familyinvitation_relationship_type"),
        ("families", "0004_emailverification"),
    ]

    operations = []
