# Generated by GPT-5 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0005_merge_email_verification_invitation_relationship_type"),
        ("relationships", "0004_alter_relationship_relationship_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyinvitation",
            name="relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent_child", "Parent → Child"),
                    ("spouse", "Spouse"),
                    ("partner", "Partner"),
                    ("ex_partner", "Ex-partner"),
                    ("co_parent", "Co-parent"),
                    ("sibling", "Sibling"),
                    ("adoptive_parent", "Adoptive Parent"),
                    ("step_parent", "Step-parent"),
                    ("guardian", "Guardian"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
