# Generated by Django 6.0.6 on 2026-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_public_discovery_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('branch_admin', 'Branch admin'), ('contributor', 'Contributor'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20),
        ),
    ]
