# Generated by Django 6.0.6 on 2026-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='memories/%Y/%m/'),
        ),
    ]
