# Generated by Django 6.0.6 on 2026-06-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent_child', 'Parent → Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('adoptive_parent', 'Adoptive Parent'), ('guardian', 'Guardian')], default='parent_child', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='families.family')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='people.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', 'from_person'], name='relationshi_family__f408a3_idx'), models.Index(fields=['family', 'to_person'], name='relationshi_family__37b796_idx'), models.Index(fields=['relationship_type'], name='relationshi_relatio_f0f539_idx')],
            },
        ),
    ]
