# Generated by Django 6.0.6 on 2026-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_familyinvitation_and_more'),
        ('people', '0001_initial'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('family', 'from_person', 'to_person', 'relationship_type'), name='unique_family_relationship_edge'),
        ),
    ]
