# Generated by Django 6.0.6 on 2026-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_relationship_unique_family_relationship_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('parent_child', 'Parent → Child'), ('spouse', 'Spouse'), ('partner', 'Partner'), ('ex_partner', 'Ex-partner'), ('sibling', 'Sibling'), ('adoptive_parent', 'Adoptive Parent'), ('step_parent', 'Step-parent'), ('guardian', 'Guardian')], default='parent_child', max_length=30),
        ),
    ]
