# Generated by GPT-5 on 2026-06-15

from itertools import combinations

from django.db import migrations, models
from django.db.models import Q


PARENT_RELATIONSHIP_TYPES = (
    "parent_child",
    "adoptive_parent",
    "step_parent",
    "guardian",
)
PARTNER_RELATIONSHIP_TYPES = (
    "spouse",
    "partner",
    "ex_partner",
    "co_parent",
)


def backfill_co_parent_relationships(apps, schema_editor):
    Relationship = apps.get_model("relationships", "Relationship")
    parent_links = Relationship.objects.filter(
        relationship_type__in=PARENT_RELATIONSHIP_TYPES,
    ).values_list("family_id", "to_person_id", "from_person_id")

    parents_by_child = {}
    for family_id, child_id, parent_id in parent_links:
        parents_by_child.setdefault((family_id, child_id), set()).add(parent_id)

    seen_pairs = set()
    for (family_id, _child_id), parent_ids in parents_by_child.items():
        for first_parent_id, second_parent_id in combinations(sorted(parent_ids), 2):
            pair_key = (family_id, first_parent_id, second_parent_id)
            if pair_key in seen_pairs:
                continue
            seen_pairs.add(pair_key)

            relationship_exists = (
                Relationship.objects.filter(
                    family_id=family_id,
                    relationship_type__in=PARTNER_RELATIONSHIP_TYPES,
                )
                .filter(
                    Q(from_person_id=first_parent_id, to_person_id=second_parent_id)
                    | Q(from_person_id=second_parent_id, to_person_id=first_parent_id)
                )
                .exists()
            )
            if relationship_exists:
                continue

            Relationship.objects.get_or_create(
                family_id=family_id,
                from_person_id=first_parent_id,
                to_person_id=second_parent_id,
                relationship_type="co_parent",
            )


class Migration(migrations.Migration):

    dependencies = [
        ("relationships", "0003_alter_relationship_relationship_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("parent_child", "Parent → Child"),
                    ("spouse", "Spouse"),
                    ("partner", "Partner"),
                    ("ex_partner", "Ex-partner"),
                    ("co_parent", "Co-parent"),
                    ("sibling", "Sibling"),
                    ("adoptive_parent", "Adoptive Parent"),
                    ("step_parent", "Step-parent"),
                    ("guardian", "Guardian"),
                ],
                default="parent_child",
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_co_parent_relationships, migrations.RunPython.noop),
    ]
